import { Manrope } from "next/font/google";
import "./_styles/global.css";
import Heading from "./_components/Heading";
import Footer from "./_components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className}  min-h-screen flex flex-col antialiased  `}
      >
        <Heading />
        <main className="relative flex-grow overflow-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
