import { Manrope } from "next/font/google";
import "./_styles/global.css";

import Providers from "./_components/Providers";
import Container from "./_components/Container";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className}  min-h-screen flex flex-col antialiased  `}
      >
        <Providers>
          <Container>
            <main className="relative flex-grow lg:overflow-hidden">
              {children}
            </main>
          </Container>
        </Providers>
      </body>
    </html>
  );
}
